# Full set of configurations
# you can also set the subscriber_queue, publisher_queue, and lazy parameters, which are optional.

# atlas robot
- ros_topic_name: "atlas/velodyne_points"
  ign_topic_name: "atlas/laser_scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ignition.msgs.PointCloudPacked"
  # subscriber_queue: 5
  # publisher_queue: 6
  # lazy: true
  direction: IGN_TO_ROS

- ros_topic_name: "atlas/imu/data"
  ign_topic_name: "atlas/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  ign_type_name: "ignition.msgs.IMU"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: IGN_TO_ROS

- ros_topic_name: "atlas/odom_ground_truth"
  ign_topic_name: "atlas/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  ign_type_name: "ignition.msgs.Odometry"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: IGN_TO_ROS

- ros_topic_name: "atlas/cmd_vel"
  ign_topic_name: "atlas/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  ign_type_name: "ignition.msgs.Twist"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: ROS_TO_IGN

# bestla robot
- ros_topic_name: "bestla/velodyne_points"
  ign_topic_name: "bestla/laser_scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ignition.msgs.PointCloudPacked"
  # subscriber_queue: 5
  # publisher_queue: 6
  # lazy: true
  direction: IGN_TO_ROS

- ros_topic_name: "bestla/imu/data"
  ign_topic_name: "bestla/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  ign_type_name: "ignition.msgs.IMU"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: IGN_TO_ROS

- ros_topic_name: "bestla/odom_ground_truth"
  ign_topic_name: "bestla/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  ign_type_name: "ignition.msgs.Odometry"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: IGN_TO_ROS

- ros_topic_name: "bestla/cmd_vel"
  ign_topic_name: "bestla/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  ign_type_name: "ignition.msgs.Twist"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: ROS_TO_IGN

- ros_topic_name: "clock"
  ign_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  ign_type_name: "ignition.msgs.Clock"
  # subscriber_queue: 10
  # publisher_queue: 20
  # lazy: false
  direction: IGN_TO_ROS

