spawn_robot_1:
  ros__parameters:
    robot_name: "atlas" # name of the robot, certain topic names are namespaced with this name
    sdf_file: "COSTAR_HUSKY_SENSOR_CONFIG_LIDAR_ONLY/model.sdf" # path to the sdf file in the share folder of the package
    world: "rubicon" # name of the world in which the robot should be spawned
    # start pose of the robot (atlas) in the world -7.0 0.0 3.96 0.0 0.0 0.0
    x: "-7.0"
    y: "0.0"
    z: "3.96"
    roll: "0.0"
    pitch: "0.0"
    yaw: "0.0"
    
spawn_robot_2:
  ros__parameters:
    robot_name: "bestla" # name of the robot, certain topic names are namespaced with this name
    sdf_file: "COSTAR_HUSKY_SENSOR_CONFIG_LIDAR_ONLY/model.sdf" # path to the sdf file in the share folder of the package
    world: "rubicon" # name of the world in which the robot should be spawned
    # start pose of the robot (bestla) in the world 0.0 -15.0 3.8 0.0 0.0 0.0
    x: "0.0"
    y: "-15.0"
    z: "3.8"
    roll: "0.0"
    pitch: "0.0"
    yaw: "0.0"

teleop_joy:
  ros__parameters:
    enable_teleop: true
    joy_config: "xbox" # "xbox" or "ps3"
    joy_dev: "/dev/input/js0" # joystick device
    cmd_vel_topic: "atlas/cmd_vel" # topic to publish the cmd_vel to
    joy_topic: "atlas/joy" # topic to subscribe to for the joystick input
