- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "Lander/gnss_rtk_rel_nav" 
  gz_topic_name: "Lander/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox1/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox1/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox2/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox2/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox3/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox3/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox4/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox4/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox5/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox5/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox6/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox6/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox7/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox7/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "RadioBox8/gnss_rtk_rel_nav" 
  gz_topic_name: "RadioBox8/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS