spawn_radio_box:
  ros__parameters:
    name: "radio_box" # name of the box, certain topic names are namespaced with this name
    sdf_file: "RADIO_BOX/model.sdf" # path to the sdf file in the share folder of the package
    world: "rubicon" # name of the world in which the robot should be spawned
    # start pose of the box in the world
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0