spawn_radio_boxes:
  ros__parameters:
    name: "radio_box" # name of the box, certain topic names are namespaced with this name, name will be automatically appended with a number
    sdf_file: "RADIO_BOX/model.sdf" # path to the sdf file in the share folder of the package
    world: "rubicon" # name of the world in which the robot should be spawned
    # start poses of the boxes in the world, each row (x, y, z, roll, pitch, yaw) is a pose of a box
    # the number of rows determines the number of boxes spawned
    poses: [
      -2.0, 0.0, 4.0, 0.0, 0.0, 0.0,
      -5.0, -4.0, 4.05, 0.0, 0.0, 0.0,
      -10.0, -6.5, 5.05, 0.0, 0.0, 0.0,
      12.32, -4.39, 4.15, 0.0, 0.0, 0.0,
      1.5, -1.7, 1.35, 0.0, 0.0, 0.0,
      0.0, 12.9, 4.22, 0.0, 0.0, 0.0,
      -7.5, 12.23, 2.72, 0.0, 0.0, 0.0,
    ]