spawn_radio_boxes:
  ros__parameters:
    lander_name: "Lander" # name of the lander, certain topic names are namespaced with this name
    radio_box_name: "RadioBox" # name of the box, certain topic names are namespaced with this name, name will be automatically appended with a number
    lander_sdf_file: "LANDER/model.sdf" # path to the sdf file in the share folder of the package
    radio_box_sdf_file: "RADIO_BOX/model.sdf" # path to the sdf file in the share folder of the package
    world: "leo_marsyard" # name of the world in which the robot should be spawned
    # start poses of the boxes in the world, each row (x, y, z, roll, pitch, yaw) is a pose of a box
    # the number of rows determines the number of boxes spawned
    lander_pose: [0.0, 0.0, 0.8, 0.0, 0.0, 0.0]
    poses: [
      -15.0, 0.0, 1.0, 0.0, 0.0, 0.0,  # 1
      -14.3, 8.0, 1.95, 0.0, 0.0, 0.0,  # 2
      8.0, -3.5, 1.85, 0.0, 0.0, 0.0,  # 3
      5.0, -10.0, 1.0, 0.0, 0.0, 0.0,  # 4
      17.0, -5.0, 1.0, 0.0, 0.0, 0.0,  # 5
      19.0, -2.5, 2.5, 0.0, 0.0, 0.0,  # 6
      3.0, 10.0, 1.0, 0.0, 0.0, 0.0,  # 7
    ]